[features]
seeds = false
skip-lint = false
[programs.localnet]
weekly_raffle_atoz = "9JfpYC24wmPGSeoNdzQh2vbz2yqjwzcmFpQxpfQ8SFA9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://radial-delicate-layer.solana-mainnet.discover.quiknode.pro/124d30642a313843475e1ac3f67e59d11d55d943"
wallet = "/home/safouene/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
